select_origin: directory
files_origin: "C:\\Users\\hdclo\\OneDrive\\Bureau\\cosmaimage"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
history: true
focus_max: 2
record_types:
  quotes:
    fill: "rgba(0, 0, 0, 0.5)"
    stroke: "rgba(0, 0, 0, 0)"
  tags:
    fill: "rgba(0, 0, 0, 0.8)"
    stroke: "rgba(0, 0, 0, 0)"
  sources:
    fill: "rgba(0, 0, 0, 0.8)"
    stroke: "rgba(0, 0, 0, 0)"
  notes:
    fill: "rgba(0, 0, 0, 0.8)"
    stroke: "rgba(0, 0, 0, 0)"
  image:
    fill: "rgba(0, 0, 0, 0.8)"
    stroke: "rgba(0, 0, 0, 1)"
  undefined:
    fill: "rgba(0, 0, 0, 0.8)"
    stroke: "rgba(0, 0, 0, 1)"
link_types:
  quotes:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
  tags:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
  sources:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
  notes:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
  image:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
  undefined:
    stroke: dash
    color: "rgba(0, 0, 0, 0.5)"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#000000"
graph_highlight_on_hover: false
graph_text_size: 6
graph_arrows: false
node_size_method: degree
node_size: 4
node_size_max: 8
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: [image]
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: ""
author: ""
description: ""
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: en
